#!/usr/bin/env python3
"""Erstellt eine bearbeitbare WaterNames.txt aus benannten Wasserobjekten."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from download_a1_motorways import (
    DEFAULT_ENDPOINT,
    DEFAULT_LATITUDE,
    DEFAULT_LONGITUDE,
    DEFAULT_RADIUS,
    OVERPASS_TIMEOUT,
    download_result,
)


def build_query(radius: int, latitude: float, longitude: float) -> str:
    return f"""[out:json][timeout:{OVERPASS_TIMEOUT}];
(
  way["natural"="water"]["name"](around:{radius}, {latitude}, {longitude});
  relation["natural"="water"]["name"](around:{radius}, {latitude}, {longitude});
  way["waterway"~"^(river|canal|dock)$"]["name"](around:{radius}, {latitude}, {longitude});
  way["landuse"="basin"]["name"](around:{radius}, {latitude}, {longitude});
  relation["landuse"="basin"]["name"](around:{radius}, {latitude}, {longitude});
);
out tags qt;"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Ermittelt benannte Wasserobjekte fuer eine WaterNames.txt."
    )
    parser.add_argument("--radius", type=int, default=DEFAULT_RADIUS)
    parser.add_argument("--latitude", type=float, default=DEFAULT_LATITUDE)
    parser.add_argument("--longitude", type=float, default=DEFAULT_LONGITUDE)
    parser.add_argument("--endpoint", default=DEFAULT_ENDPOINT)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("input/WaterNames.txt"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        query = build_query(args.radius, args.latitude, args.longitude)
        print("Suche benannte Wasserobjekte ...")
        data = json.loads(download_result(args.endpoint, query))
        names = sorted(
            {
                element.get("tags", {}).get("name", "").strip()
                for element in data.get("elements", [])
                if element.get("tags", {}).get("name", "").strip()
            },
            key=str.casefold,
        )
        if not names:
            raise RuntimeError("Keine benannten Wasserobjekte gefunden.")
        args.output.parent.mkdir(parents=True, exist_ok=True)
        content = (
            "# Generated by discover_water_names.py.\n"
            "# Gewaessernamen pruefen und ungewuenschte Zeilen entfernen.\n"
            + "\n".join(names)
            + "\n"
        )
        args.output.write_text(content, encoding="utf-8")
        print(f"{len(names)} Namen gespeichert: {args.output.resolve()}")
    except (OSError, RuntimeError, json.JSONDecodeError) as exc:
        print(f"Fehler: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
