#pragma once

#include <cstddef>
#include <cstdint>

struct MapPoint {
    float lat;
    float lon;
};

enum class MapRoadKind : uint8_t {
    kMotorway,
    kPrimary,
};

struct MapRoad {
    const char* id;
    const MapPoint* points;
    size_t point_count;
    MapRoadKind kind;
};

// Generated by reduce_motorways_for_display.py
// Coordinates are latitude/longitude in decimal degrees.
// Map data (c) OpenStreetMap contributors, ODbL.

// A1, simplified orientation centreline.
constexpr MapPoint kRoadA1[] = {
    {51.240666f, 7.229083f},
    {51.248085f, 7.226555f},
    {51.255280f, 7.230527f},
    {51.268545f, 7.250384f},
    {51.277088f, 7.256160f},
    {51.297323f, 7.261215f},
    {51.305417f, 7.264464f},
    {51.312611f, 7.272046f},
    {51.320480f, 7.289015f},
    {51.328125f, 7.309233f},
    {51.352406f, 7.361945f},
    {51.376014f, 7.424766f},
    {51.383883f, 7.437041f},
    {51.391302f, 7.442096f},
    {51.397822f, 7.452566f},
    {51.408839f, 7.490475f},
    {51.414909f, 7.505278f},
    {51.423003f, 7.518636f},
    {51.432671f, 7.529467f},
    {51.450657f, 7.542104f},
    {51.462348f, 7.578208f},
    {51.469768f, 7.595899f},
    {51.493600f, 7.633086f},
    {51.506415f, 7.646805f},
    {51.524177f, 7.657275f},
    {51.564197f, 7.666301f},
    {51.575213f, 7.671356f},
    {51.582408f, 7.677854f},
    {51.593874f, 7.683992f},
    {51.612085f, 7.687603f},
    {51.637491f, 7.685797f},
    {51.665595f, 7.680743f},
    {51.686954f, 7.673161f},
    {51.706514f, 7.660886f},
};

// A2, simplified orientation centreline.
constexpr MapPoint kRoadA2[] = {
    {51.618381f, 7.789055f},
    {51.605341f, 7.717930f},
    {51.592076f, 7.608174f},
    {51.580384f, 7.527301f},
    {51.575888f, 7.476756f},
    {51.577686f, 7.454732f},
    {51.581958f, 7.426210f},
    {51.586455f, 7.370249f},
    {51.591401f, 7.350031f},
    {51.601294f, 7.327285f},
    {51.603092f, 7.318620f},
    {51.603542f, 7.309594f},
    {51.593649f, 7.247857f},
    {51.577462f, 7.161929f},
    {51.567794f, 7.091888f},
    {51.562623f, 7.063004f},
    {51.558801f, 7.033760f},
    {51.558126f, 7.001267f},
};

// A40, simplified orientation centreline.
constexpr MapPoint kRoadA40[] = {
    {51.497422f, 7.444262f},
    {51.496972f, 7.382885f},
    {51.496298f, 7.369888f},
    {51.492925f, 7.353280f},
    {51.495848f, 7.330535f},
    {51.496523f, 7.309233f},
    {51.494724f, 7.244607f},
    {51.495399f, 7.235220f},
    {51.497197f, 7.226555f},
    {51.497647f, 7.213197f},
    {51.496073f, 7.196228f},
    {51.492925f, 7.186480f},
    {51.485056f, 7.182508f},
    {51.482358f, 7.178537f},
    {51.479211f, 7.168428f},
    {51.475838f, 7.148932f},
    {51.470442f, 7.100553f},
    {51.451332f, 7.022929f},
    {51.444812f, 6.987547f},
};

// A42, simplified orientation centreline.
constexpr MapPoint kRoadA42[] = {
    {51.503043f, 6.983576f},
    {51.516757f, 7.054339f},
    {51.522153f, 7.068781f},
    {51.528224f, 7.076724f},
    {51.531821f, 7.083584f},
    {51.533844f, 7.092971f},
    {51.536093f, 7.104885f},
    {51.538116f, 7.129436f},
    {51.542613f, 7.169150f},
    {51.547334f, 7.200560f},
    {51.555203f, 7.231610f},
    {51.558576f, 7.248579f},
    {51.558126f, 7.273851f},
    {51.562173f, 7.338116f},
    {51.561948f, 7.351475f},
    {51.560374f, 7.361945f},
};

// A43, simplified orientation centreline.
constexpr MapPoint kRoadA43[] = {
    {51.695722f, 7.147849f},
    {51.665145f, 7.160124f},
    {51.647834f, 7.170955f},
    {51.629847f, 7.168067f},
    {51.620404f, 7.168428f},
    {51.612310f, 7.173121f},
    {51.604216f, 7.180703f},
    {51.586455f, 7.187924f},
    {51.557677f, 7.196950f},
    {51.519006f, 7.211753f},
    {51.514959f, 7.215363f},
    {51.505066f, 7.249662f},
    {51.498096f, 7.267714f},
    {51.490003f, 7.275657f},
    {51.456278f, 7.290098f},
    {51.447285f, 7.292625f},
    {51.440540f, 7.292264f},
    {51.420980f, 7.269880f},
    {51.409738f, 7.263020f},
    {51.382534f, 7.261937f},
    {51.369718f, 7.272046f},
    {51.363198f, 7.274935f},
    {51.355329f, 7.274573f},
    {51.313736f, 7.266270f},
};

// A44, simplified orientation centreline.
constexpr MapPoint kRoadA44[] = {
    {51.522153f, 7.651499f},
    {51.520580f, 7.689408f},
    {51.526200f, 7.720818f},
    {51.527999f, 7.737065f},
    {51.525076f, 7.787610f},
    {51.533620f, 7.841044f},
};

// A448, simplified orientation centreline.
constexpr MapPoint kRoadA448[] = {
    {51.480785f, 7.179981f},
    {51.477862f, 7.184675f},
    {51.462124f, 7.200560f},
    {51.457627f, 7.206698f},
    {51.454929f, 7.215363f},
    {51.455828f, 7.225833f},
    {51.461899f, 7.249662f},
    {51.463023f, 7.260493f},
    {51.463248f, 7.272768f},
    {51.458526f, 7.329451f},
    {51.458526f, 7.354363f},
    {51.459426f, 7.374220f},
    {51.460550f, 7.391550f},
    {51.463023f, 7.408880f},
};

// A45, simplified orientation centreline.
constexpr MapPoint kRoadA45[] = {
    {51.263823f, 7.602758f},
    {51.273491f, 7.596621f},
    {51.280910f, 7.587956f},
    {51.285407f, 7.580374f},
    {51.290128f, 7.563405f},
    {51.293276f, 7.556545f},
    {51.298897f, 7.554379f},
    {51.312387f, 7.553657f},
    {51.316434f, 7.548602f},
    {51.321380f, 7.539576f},
    {51.328350f, 7.531272f},
    {51.349259f, 7.523330f},
    {51.362074f, 7.515387f},
    {51.394674f, 7.528745f},
    {51.405466f, 7.543909f},
    {51.410862f, 7.549685f},
    {51.416483f, 7.550769f},
    {51.422104f, 7.548241f},
    {51.426600f, 7.543909f},
    {51.431547f, 7.534522f},
    {51.437392f, 7.520802f},
    {51.441214f, 7.505278f},
    {51.442563f, 7.483254f},
    {51.443238f, 7.442457f},
    {51.445711f, 7.433431f},
    {51.472466f, 7.400215f},
    {51.479436f, 7.392633f},
    {51.494949f, 7.387218f},
    {51.502368f, 7.387218f},
    {51.509113f, 7.389023f},
    {51.515633f, 7.387218f},
    {51.541938f, 7.364833f},
    {51.551606f, 7.359418f},
    {51.561948f, 7.359418f},
    {51.586230f, 7.367361f},
};

// A46, simplified orientation centreline.
constexpr MapPoint kRoadA46[] = {
    {51.387705f, 7.726956f},
    {51.387030f, 7.707821f},
    {51.384557f, 7.690491f},
    {51.366571f, 7.580013f},
    {51.365896f, 7.562683f},
    {51.367920f, 7.544631f},
    {51.369044f, 7.524052f},
    {51.373765f, 7.497696f},
};

// A52, simplified orientation centreline.
constexpr MapPoint kRoadA52[] = {
    {51.451332f, 7.039537f},
    {51.443238f, 7.036649f},
    {51.438741f, 7.033399f},
    {51.426376f, 7.012098f},
    {51.423003f, 7.002350f},
    {51.423228f, 6.993685f},
};

// A535, simplified orientation centreline.
constexpr MapPoint kRoadA535[] = {
    {51.323178f, 7.068420f},
    {51.331047f, 7.065171f},
    {51.339366f, 7.057589f},
    {51.350158f, 7.042425f},
};

constexpr MapRoad kMapRoads[] = {
    {"A1", kRoadA1, sizeof(kRoadA1) / sizeof(kRoadA1[0]),
    MapRoadKind::kMotorway},
    {"A2", kRoadA2, sizeof(kRoadA2) / sizeof(kRoadA2[0]),
    MapRoadKind::kMotorway},
    {"A40", kRoadA40, sizeof(kRoadA40) / sizeof(kRoadA40[0]),
    MapRoadKind::kMotorway},
    {"A42", kRoadA42, sizeof(kRoadA42) / sizeof(kRoadA42[0]),
    MapRoadKind::kMotorway},
    {"A43", kRoadA43, sizeof(kRoadA43) / sizeof(kRoadA43[0]),
    MapRoadKind::kMotorway},
    {"A44", kRoadA44, sizeof(kRoadA44) / sizeof(kRoadA44[0]),
    MapRoadKind::kMotorway},
    {"A448", kRoadA448, sizeof(kRoadA448) / sizeof(kRoadA448[0]),
    MapRoadKind::kMotorway},
    {"A45", kRoadA45, sizeof(kRoadA45) / sizeof(kRoadA45[0]),
    MapRoadKind::kMotorway},
    {"A46", kRoadA46, sizeof(kRoadA46) / sizeof(kRoadA46[0]),
    MapRoadKind::kMotorway},
    {"A52", kRoadA52, sizeof(kRoadA52) / sizeof(kRoadA52[0]),
    MapRoadKind::kMotorway},
    {"A535", kRoadA535, sizeof(kRoadA535) / sizeof(kRoadA535[0]),
    MapRoadKind::kMotorway},
};

constexpr size_t kMapRoadCount =
    sizeof(kMapRoads) / sizeof(kMapRoads[0]);
